# Generated by Django 2.0 on 2022-03-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_auto_20220314_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_description',
            field=models.CharField(max_length=500),
        ),
    ]
